import React, { useState } from 'react';
import { Github, X, Loader2, CheckCircle2 } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { pushToGitHub, GitHubConfig } from '../lib/github';
import { GeneratedFile } from '../services/ai';

interface GitHubModalProps {
  isOpen: boolean;
  onClose: () => void;
  files: GeneratedFile[];
  defaultRepoName: string;
}

export function GitHubModal({ isOpen, onClose, files, defaultRepoName }: GitHubModalProps) {
  const [config, setConfig] = useState<GitHubConfig>({
    token: '',
    repoName: defaultRepoName.toLowerCase().replace(/\s+/g, '-'),
    description: 'Generated by DevHive Builder',
    isPrivate: false,
  });
  
  const [status, setStatus] = useState<'idle' | 'pushing' | 'success' | 'error'>('idle');
  const [progressMsg, setProgressMsg] = useState('');
  const [repoUrl, setRepoUrl] = useState('');

  const handlePush = async () => {
    if (!config.token || !config.repoName) return;
    
    setStatus('pushing');
    try {
      const url = await pushToGitHub(config, files, setProgressMsg);
      setRepoUrl(url);
      setStatus('success');
    } catch (error) {
      setProgressMsg(error instanceof Error ? error.message : 'Failed to push to GitHub');
      setStatus('error');
    }
  };

  if (!isOpen) return null;

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          exit={{ opacity: 0, scale: 0.95 }}
          className="w-full max-w-md overflow-hidden rounded-2xl border border-zinc-800 bg-[#1e1e1e] shadow-2xl"
        >
          <div className="flex items-center justify-between border-b border-zinc-800 px-6 py-4">
            <div className="flex items-center gap-2 text-white">
              <Github size={20} />
              <h3 className="font-bold">Push to GitHub</h3>
            </div>
            <button onClick={onClose} className="text-zinc-400 hover:text-white">
              <X size={20} />
            </button>
          </div>

          <div className="p-6 space-y-4">
            {status === 'success' ? (
              <div className="flex flex-col items-center justify-center py-8 text-center">
                <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-green-500/10 text-green-500">
                  <CheckCircle2 size={32} />
                </div>
                <h4 className="mb-2 text-xl font-bold text-white">Successfully Pushed!</h4>
                <p className="mb-6 text-sm text-zinc-400">Your project is now live on GitHub.</p>
                <a
                  href={repoUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="rounded-lg bg-white px-6 py-2.5 text-sm font-medium text-black hover:bg-zinc-200 transition-colors"
                >
                  View Repository
                </a>
              </div>
            ) : (
              <>
                <div>
                  <label className="mb-1.5 block text-xs font-medium text-zinc-400">Personal Access Token</label>
                  <input
                    type="password"
                    value={config.token}
                    onChange={(e) => setConfig({ ...config, token: e.target.value })}
                    placeholder="ghp_..."
                    className="w-full rounded-lg border border-zinc-700 bg-zinc-800/50 px-3 py-2 text-sm text-white placeholder-zinc-500 focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
                  />
                  <p className="mt-1.5 text-[10px] text-zinc-500">
                    Needs 'repo' scope. Tokens are not stored and only used for this request.
                  </p>
                </div>

                <div>
                  <label className="mb-1.5 block text-xs font-medium text-zinc-400">Repository Name</label>
                  <input
                    type="text"
                    value={config.repoName}
                    onChange={(e) => setConfig({ ...config, repoName: e.target.value })}
                    className="w-full rounded-lg border border-zinc-700 bg-zinc-800/50 px-3 py-2 text-sm text-white placeholder-zinc-500 focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
                  />
                </div>

                <div>
                  <label className="mb-1.5 block text-xs font-medium text-zinc-400">Description</label>
                  <input
                    type="text"
                    value={config.description}
                    onChange={(e) => setConfig({ ...config, description: e.target.value })}
                    className="w-full rounded-lg border border-zinc-700 bg-zinc-800/50 px-3 py-2 text-sm text-white placeholder-zinc-500 focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
                  />
                </div>

                <div className="flex items-center gap-2 pt-2">
                  <input
                    type="checkbox"
                    id="isPrivate"
                    checked={config.isPrivate}
                    onChange={(e) => setConfig({ ...config, isPrivate: e.target.checked })}
                    className="rounded border-zinc-700 bg-zinc-800 text-blue-500 focus:ring-blue-500 focus:ring-offset-zinc-900"
                  />
                  <label htmlFor="isPrivate" className="text-sm text-zinc-300">
                    Make repository private
                  </label>
                </div>

                {status === 'error' && (
                  <div className="rounded-lg bg-red-500/10 p-3 text-sm text-red-500">
                    {progressMsg}
                  </div>
                )}

                <button
                  onClick={handlePush}
                  disabled={status === 'pushing' || !config.token || !config.repoName}
                  className="mt-4 flex w-full items-center justify-center gap-2 rounded-lg bg-white px-4 py-2.5 text-sm font-medium text-black hover:bg-zinc-200 disabled:opacity-50 transition-colors"
                >
                  {status === 'pushing' ? (
                    <>
                      <Loader2 size={16} className="animate-spin" />
                      {progressMsg || 'Pushing...'}
                    </>
                  ) : (
                    <>
                      <Github size={16} />
                      Push to GitHub
                    </>
                  )}
                </button>
              </>
            )}
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
